export const MAINPAGE_ROUTE = '/'
export const ABOUTUS_ROUTE = '/about_us'
export const ORDER_ROUTE = '/order'
export const BOOSTER_ROUTE = '/booster'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const PROFILE_ROUTE = 'profile'
